#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Build script for H3SaveWatcher
# Reads secrets and config from .env (never committed).
# Generates src/buildvars.go with all build-time values, then compiles.
#
# Modes:
#   ./build.sh              — local build, current OS/arch, fast
#   RELEASE=1 ./build.sh    — cross-platform release via fyne-cross (Docker required)
#
# All output goes to build/:
#   build/h3savewatcher                   (local)
#   build/h3savewatcher-linux-amd64       (release)
#   build/h3savewatcher-darwin-amd64      (release)
#   build/h3savewatcher-darwin-arm64      (release)
#   build/h3savewatcher-windows-amd64.exe (release)
#   build/checksums.txt                   (release)
# ---------------------------------------------------------------------------

if [ ! -f .env ]; then
  echo "ERROR: .env file not found. Copy .env.example to .env and fill in values." >&2
  exit 1
fi

set -o allexport
source .env
set +o allexport

: "${API_USER:?API_USER not set in .env}"
: "${API_PASSWORD:?API_PASSWORD not set in .env}"
: "${VERSION:?VERSION not set in .env}"
: "${GITHUB_REPO:?GITHUB_REPO not set in .env}"

# Strip "v" prefix for fyne-cross -app-version (expects "1.2.3" not "v1.2.3")
APP_VERSION="${VERSION#v}"

# ---------------------------------------------------------------------------
# Generate src/buildvars.go — holds all values that previously required
# -ldflags -X injection. This file is gitignored and recreated every build.
# ---------------------------------------------------------------------------
cat > src/buildvars.go <<EOF
// Code generated by build.sh. DO NOT EDIT.
package main

var (
	apiUser     = "${API_USER}"
	apiPassword = "${API_PASSWORD}"
	appVersion  = "${VERSION}"
	githubRepo  = "${GITHUB_REPO}"
)
EOF

echo "Generated src/buildvars.go (version=${VERSION})"

mkdir -p build

if [ "${RELEASE:-}" = "1" ]; then
  # ---------------------------------------------------------------------------
  # Cross-platform release build via fyne-cross.
  # Requires Docker running. Install fyne-cross: go install github.com/fyne-io/fyne-cross@latest
  # ---------------------------------------------------------------------------
  echo "Building release ${VERSION} for all platforms via fyne-cross..."

  fyne-cross linux   -arch amd64       -icon src/Icon.png -app-version "${APP_VERSION}" ./src/
  fyne-cross darwin  -arch amd64,arm64 -icon src/Icon.png -app-version "${APP_VERSION}" ./src/
  fyne-cross windows -arch amd64       -icon src/Icon.png -app-version "${APP_VERSION}" ./src/

  echo "Copying and renaming artifacts..."
  cp fyne-cross/bin/linux-amd64/src                 build/h3savewatcher-linux-amd64
  cp fyne-cross/bin/darwin-amd64/src                build/h3savewatcher-darwin-amd64
  cp fyne-cross/bin/darwin-arm64/src                build/h3savewatcher-darwin-arm64
  cp fyne-cross/bin/windows-amd64/H3SaveWatcher.exe build/h3savewatcher-windows-amd64.exe

  echo "Generating checksums..."
  ( cd build && sha256sum \
    h3savewatcher-linux-amd64 \
    h3savewatcher-darwin-amd64 \
    h3savewatcher-darwin-arm64 \
    h3savewatcher-windows-amd64.exe \
    > checksums.txt )

  echo ""
  echo "build/checksums.txt:"
  cat build/checksums.txt
  echo ""
  echo "Upload all files from build/ to the GitHub release tagged ${VERSION}."
else
  # ---------------------------------------------------------------------------
  # Local build — current OS/arch, output as build/h3savewatcher
  # No Docker needed.
  # ---------------------------------------------------------------------------
  go build -o build/h3savewatcher ./src/
  echo "Built build/h3savewatcher (${VERSION})"
fi
